name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Get submodules
      run: git submodule update --init --recursive

    - name: Update apt
      run: sudo apt-get update --fix-missing
    
    - name: Install tree
      run: sudo apt-get install tree 

    - name: Install norminette
      run: pip install norminette

    - name: Run tree
      run: tree

    - name: Run norminette
      run: norminette src include libft/src libft/include

    - name: Make program
      run: make

    - name: Re-make program
      run: make re

    - name: View Contents of Libft
      run: nm -C libft/build/libft.a
